### ISSUE TITLE
Error when trying run npm run dev

### ISSUE THREAD

**Issue by hvquy001** [perpetual-protocol/perpetual-protocol#9]
Hi Dev Team,

I'm trying to run the local development, but I faced this error:

deploy clearing house...
deployUpgradableContract src/ClearingHouse.sol:ClearingHouse:[100000000000000000,62500000000000000,12500000000000000,0xB7f8BC63BbcaD18155201308C8f3540b07f84F5e,0x5FC8d32690cc91D4c39d9d3abcBD16989F875707]
An unexpected error occurred:

Error: The requested contract was not found. Make sure the source code is available for compilation
    at getContractNameAndRunValidation (/Users/hoangquy/Downloads/CODE/perpetual-protocol/node_modules/@openzeppelin/hardhat-upgrades/node_modules/@openzeppelin/upgrades-core/src/validate/query.ts:46:11)
    at Object.assertUpgradeSafe (/Users/hoangquy/Downloads/CODE/perpetual-protocol/node_modules/@openzeppelin/hardhat-upgrades/node_modules/@openzeppelin/upgrades-core/src/validate/query.ts:11:26)
    at Proxy.deployProxy (/Users/hoangquy/Downloads/CODE/perpetual-protocol/node_modules/@openzeppelin/hardhat-upgrades/src/deploy-proxy.ts:43:5)
    at OzContractDeployer.deploy (/Users/hoangquy/Downloads/CODE/perpetual-protocol/publish/OzContractDeployer.ts:27:31)
    at ContractWrapper.deployUpgradableContract (/Users/hoangquy/Downloads/CODE/perpetual-protocol/publish/contract/ContractWrapper.ts:36:25)
    at /Users/hoangquy/Downloads/CODE/perpetual-protocol/publish/migrations/0001-layer2-deployBasicContracts.ts:64:13
    at executeMigration (/Users/hoangquy/Downloads/CODE/perpetual-protocol/publish/Migration.ts:95:9)
    at migrate (/Users/hoangquy/Downloads/CODE/perpetual-protocol/publish/Migration.ts:164:9)
    at SimpleTaskDefinition.action (/Users/hoangquy/Downloads/CODE/perpetual-protocol/hardhat.config.ts:78:9)
    at Environment._runTaskDefinition (/Users/hoangquy/Downloads/CODE/perpetual-protocol/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
An unexpected error occurred:
Error: The requested contract was not found. Make sure the source code is available for compilation
    at getContractNameAndRunValidation (/Users/hoangquy/Downloads/CODE/perpetual-protocol/node_modules/@openzeppelin/hardhat-upgrades/node_modules/@openzeppelin/upgrades-core/src/validate/query.ts:46:11)
    at Object.assertUpgradeSafe (/Users/hoangquy/Downloads/CODE/perpetual-protocol/node_modules/@openzeppelin/hardhat-upgrades/node_modules/@openzeppelin/upgrades-core/src/validate/query.ts:11:26)
    at Proxy.deployProxy (/Users/hoangquy/Downloads/CODE/perpetual-protocol/node_modules/@openzeppelin/hardhat-upgrades/src/deploy-proxy.ts:43:5)
    at OzContractDeployer.deploy (/Users/hoangquy/Downloads/CODE/perpetual-protocol/publish/OzContractDeployer.ts:27:31)
    at ContractWrapper.deployUpgradableContract (/Users/hoangquy/Downloads/CODE/perpetual-protocol/publish/contract/ContractWrapper.ts:36:25)
    at /Users/hoangquy/Downloads/CODE/perpetual-protocol/publish/migrations/0001-layer2-deployBasicContracts.ts:64:13
    at executeMigration (/Users/hoangquy/Downloads/CODE/perpetual-protocol/publish/Migration.ts:95:9)
    at migrate (/Users/hoangquy/Downloads/CODE/perpetual-protocol/publish/Migration.ts:164:9)
    at SimpleTaskDefinition.action (/Users/hoangquy/Downloads/CODE/perpetual-protocol/hardhat.config.ts:78:9)
    at Environment._runTaskDefinition (/Users/hoangquy/Downloads/CODE/perpetual-protocol/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @perp/contract@0.13.1 dev: `ts-node --files scripts/dev.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @perp/contract@0.13.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hoangquy/.npm/_logs/2021-05-27T10_51_04_235Z-debug.log

I already run 
`npm install`

`npm run build`

The source is the original on Github.

I'm using Node `v12.14.1`

**Comment by hvquy001** [comment]
Follow this instruction should work
https://github.com/perpetual-protocol/perpetual-protocol/issues/3#issuecomment-847162682
